# Generated by Django 4.2.13 on 2024-05-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LLMapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gemma2bQlora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.CharField(max_length=3000)),
                ("response", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Gemma7bLora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.CharField(max_length=3000)),
                ("response", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Gemmas7bQlora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.CharField(max_length=3000)),
                ("response", models.TextField()),
            ],
        ),
    ]
